apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          # Image is replaced by CI/CD pipeline at deploy time
          #image: <ecr_registry>/eks-statuspage/backend:latest
          image: 207137402976.dkr.ecr.eu-west-2.amazonaws.com/eks-statuspage/backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: postgres-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
